In [17]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
from datetime import datetime as dt
from datetime import timedelta

In [18]:
stock_lists = pd.read_csv(r'C:\Users\44738\Desktop\Desktop Files\Dissertation\test_stock_list.csv', encoding='latin1')

In [20]:
symbols = list(stock_lists)

all_returns = {}

end = dt.today() 
start = end - timedelta(days=365)

print(f'Getting returns and impact scores for {len(symbols)} stocks')

return_data = {}

Getting returns and impact scores for 1 stocks

In [6]:
soup =

Collecting tokenizer
  Downloading tokenizer-3.2.0-py2.py3-none-any.whl (77 kB)
Installing collected packages: tokenizer
Successfully installed tokenizer-3.2.0

NameError: name 'tokenizer' is not defined

In [40]:
import pandas as pd 
import time
import datetime
test_list = pd.read_csv(r'C:\Users\44738\Desktop\Desktop Files\Dissertation\test_stock_list.csv', encoding='latin1')


# symbols = list(table[0]['Symbol'])

# for symbol in symbols[0:5]:
#     print(symbol)
symbols = []
temp = list(test_list['stock'])
temp = ['^GSPC']
for i in temp:
    j = i.lstrip()
    symbols.append(j)

In [41]:
interval = '1d'
period1 = int(time.mktime(datetime.datetime(2016, 7, 1, 23, 59).timetuple()))
period2 = int(time.mktime(datetime.datetime(2021, 7, 1, 23, 59).timetuple()))
bs_data = pd.DataFrame()

xlwriter = pd.ExcelWriter('historical prices.xlsx', engine='openpyxl')
for ticker in symbols:
    try:
        query_string = f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'
        df = pd.read_csv(query_string)
        df.drop(columns=['Open', 'Close', 'Low', 'High', 'Volume'], inplace=True)
        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date', inplace=True)
        df.rename(columns={'Adj Close': ticker}, inplace=True)
        bs_data = pd.concat([bs_data, df], axis=1)
    except:
        print('No data for: ', ticker)

In [42]:
bs_data

                  ^GSPC
Date
2016-07-01  2102.949951
2016-07-05  2088.550049
2016-07-06  2099.729980
2016-07-07  2097.899902
2016-07-08  2129.899902
...                 ...
2021-06-25  4280.700195
2021-06-28  4290.609863
2021-06-29  4291.799805
2021-06-30  4297.500000
2021-07-01  4319.939941

[1259 rows x 1 columns]

In [32]:
bs_returns = bs_data.pct_change()[1:]
weights = [1/len(bs_data.columns)] * len(bs_data.columns)

bs_weighted = (weights * bs_returns)
bs_weighted

,MKTX,MSCI,ZION,SIVB,AFL,L,BEN,UNM,SCHW,RF,...,DTE,ETR,AES,NEE,PNW,ED,FE,EVRG,WEC,NI
Date,,,,,,,,,,,,,,,,,,,,,
2016-07-05,0.000033,-0.000009,-0.000279,-1.930961e-04,-0.000065,-0.000102,-0.000109,-0.000182,-0.000144,-0.000191,...,0.000039,0.000007,-0.000049,4.125523e-05,0.000086,0.000068,0.000007,1.668373e-06,0.000056,0.000019
2016-07-06,0.000177,0.000051,0.000110,2.399844e-05,0.000047,0.000013,0.000033,0.000029,0.000064,0.000100,...,-0.000007,0.000017,0.000012,7.174685e-07,-0.000001,-0.000007,0.000059,-8.335450e-07,-0.000012,-0.000021
2016-07-07,-0.000024,0.000050,0.000082,1.401446e-04,-0.000051,0.000000,0.000010,-0.000023,0.000112,0.000034,...,-0.000083,-0.000088,-0.000050,-9.182290e-05,-0.000090,-0.000090,-0.000038,4.172117e-06,-0.000091,-0.000107
2016-07-08,0.000077,0.000060,0.000063,8.769726e-05,0.000070,0.000076,0.000199,0.000111,0.000087,0.000108,...,0.000045,0.000022,0.000085,5.853336e-05,0.000013,0.000023,0.000092,8.336037e-06,0.000047,0.000016
2016-07-11,-0.000028,-0.000004,0.000036,5.887732e-05,0.000011,-0.000017,-0.000004,0.000015,0.000009,0.000072,...,-0.000009,0.000008,0.000088,-8.671092e-06,-0.000005,-0.000011,0.000012,-2.496595e-06,-0.000009,-0.000011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-25,0.000070,-0.000012,0.000110,3.071128e-05,0.000094,0.000043,0.000094,0.000149,0.000025,0.000065,...,0.000037,0.000029,0.000045,6.313060e-05,0.000065,0.000028,0.000064,2.141658e-05,0.000054,0.000049
2021-06-28,0.000017,0.000024,-0.000172,-6.509650e-05,-0.000074,-0.000094,-0.000091,-0.000147,-0.000032,-0.000059,...,-0.000010,0.000035,0.000056,8.199760e-05,0.000006,-0.000003,0.000046,4.568603e-06,0.000045,0.000011
2021-06-29,0.000025,0.000068,-0.000066,8.439036e-08,0.000016,-0.000009,-0.000049,-0.000038,-0.000004,-0.000065,...,-0.000054,-0.000086,-0.000028,-6.684596e-05,-0.000075,-0.000113,-0.000064,-8.215223e-05,-0.000100,-0.000097
2021-06-30,-0.000085,-0.000079,0.000014,-3.878194e-06,0.000010,0.000021,0.000010,0.000037,-0.000026,0.000028,...,0.000004,-0.000036,-0.000053,-5.070036e-05,0.000032,-0.000022,-0.000041,-1.625829e-05,-0.000004,-0.000027
2021-07-01,0.000006,0.000008,0.000085,7.129633e-05,0.000030,0.000047,0.000040,0.000071,0.000049,0.000058,...,0.000067,0.000088,0.000047,5.830124e-05,0.000064,0.000054,0.000057,7.458275e-05,0.000065,0.000057

In [33]:
bs_portfolio = pd.DataFrame(bs_weighted.sum(axis=1)).rename(columns={0:'Screened_SP500'})
bs_portfolio

            Screened_SP500
Date
2016-07-05       -0.009549
2016-07-06        0.005379
2016-07-07        0.000815
2016-07-08        0.018923
2016-07-11        0.004479
...                    ...
2021-06-25        0.007165
2021-06-28       -0.002619
2021-06-29       -0.000230
2021-06-30        0.000866
2021-07-01        0.007748

[1258 rows x 1 columns]

In [34]:
sp_us_list = pd.read_csv(r'C:\Users\44738\Desktop\Desktop Files\Dissertation\test_stock_list.csv', encoding='latin1')

# symbols = list(table[0]['Symbol'])

# for symbol in symbols[0:5]:
#     print(symbol)
symbols = []
temp = list(sp_us_list['stock'])
for i in temp:
    j = i.lstrip()
    symbols.append(j)

In [35]:
interval = '1d'
period1 = int(time.mktime(datetime.datetime(2016, 7, 1, 23, 59).timetuple()))
period2 = int(time.mktime(datetime.datetime(2021, 7, 1, 23, 59).timetuple()))
sp_us = pd.DataFrame()

xlwriter = pd.ExcelWriter('historical prices.xlsx', engine='openpyxl')
for ticker in symbols:
    try:
        query_string = f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'
        df = pd.read_csv(query_string)
        df.drop(columns=['Open', 'Close', 'Low', 'High', 'Volume'], inplace=True)
        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date', inplace=True)
        df.rename(columns={'Adj Close': ticker}, inplace=True)
        sp_us = pd.concat([bs_data, df], axis=1)
    except:
        print('No data for: ', ticker)

No data for:  MKTX
No data for:  AVY
No data for:  DRI
No data for:  CFG
No data for:  VTRS
No data for:  STX
No data for:  GPC
No data for:  NTAP
No data for:  ABC
No data for:  TFX
No data for:  NVR
No data for:  CE
No data for:  HES
No data for:  BBWI
No data for:  MTB
No data for:  CCL
No data for:  CZR
No data for:  J
No data for:  K
No data for:  RCL
No data for:  IEX
No data for:  BIO
No data for:  CAG
No data for:  PFG
No data for:  RJF
No data for:  HAL
No data for:  BXP
No data for:  TXT
No data for:  AES
No data for:  UDR
No data for:  EVRG
No data for:  MGM
No data for:  MAS
No data for:  LNT
No data for:  OMC
No data for:  WAB
No data for:  ABMD
No data for:  CAH
No data for:  CNP
No data for:  NLOK
No data for:  DVN
No data for:  EMN
No data for:  BKR
No data for:  SJM
No data for:  JBHT
No data for:  LKQ
No data for:  IPG
No data for:  UAL
No data for:  INCY
No data for:  WHR
No data for:  PKG
No data for:  PHM
No data for:  CBOE
No data for:  AAP
No data for:  FBHS
No data for:  JKHY
No data for:  PTC
No data for:  PWR
No data for:  IRM
No data for:  XRAY
No data for:  HRL
No data for:  PNR
No data for:  ATO
No data for:  LDOS
No data for:  WRK
No data for:  ALLE
No data for:  KIM
No data for:  CTXS
No data for:  BF-B
No data for:  L
No data for:  HWM
No data for:  FANG
No data for:  HAS
No data for:  FOXA
No data for:  LVS
No data for:  AAL
No data for:  FFIV
No data for:  LNC
No data for:  CHRW
No data for:  UHS
No data for:  SNA
No data for:  MHK
No data for:  RHI
No data for:  FMC
No data for:  LYV
No data for:  LUMN
No data for:  TPR
No data for:  RE
No data for:  HSIC
No data for:  WRB
No data for:  HST
No data for:  NRG
No data for:  DISH
No data for:  MOS
No data for:  REG
No data for:  BWA
No data for:  AIZ
No data for:  CMA
No data for:  NI
No data for:  PENN
No data for:  LW
No data for:  DVA
No data for:  JNPR
No data for:  AOS
No data for:  WYNN
No data for:  CF
No data for:  SEE
No data for:  NWL
No data for:  TAP
No data for:  PNW
No data for:  GL
No data for:  DXC
No data for:  WU
No data for:  IVZ
No data for:  CPB
No data for:  ZION
No data for:  OGN
No data for:  ROL
No data for:  NWSA
No data for:  MRO
No data for:  NCLH
No data for:  BEN
No data for:  HII
No data for:  NLSN
No data for:  FRT
No data for:  DISCK
No data for:  PVH
No data for:  ALK
No data for:  PBCT
No data for:  HBI
No data for:  VNO
No data for:  LEG
No data for:  APA
No data for:  IPGP
No data for:  COG
No data for:  GPS
No data for:  RL
No data for:  PRGO
No data for:  UNM
No data for:  FOX
No data for:  NOV
No data for:  DISCA
No data for:  UAA
No data for:  UA
No data for:  NVCR
No data for:  ATUS
No data for:  MTN
No data for:  CHWY
No data for:  HEI
No data for:  PPD
No data for:  SIRI
No data for:  ZI
No data for:  ZG
No data for:  SEIC
No data for:  WMG
No data for:  OPEN
No data for:  VMEO
No data for:  AFRM
No data for:  BF-A
No data for:  BMBL
No data for:  IBKR
No data for:  LBRDA
No data for:  APP
No data for:  UI
No data for:  GDRX
No data for:  QS
No data for:  XM

In [39]:
bs_data

,MKTX,MSCI,ZION,SIVB,AFL,L,BEN,UNM,SCHW,RF,...,GWW,RF,TTWO,HPE,IR,OXY,CMS,AKAM,CINF,WDC
Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01,138.653778,72.700638,22.131779,93.849998,32.020912,39.772305,25.784170,26.412302,23.563480,7.143428,...,207.046677,7.143428,37.919998,9.366409,NaN,61.357540,39.298100,55.500000,64.849022,40.987659
2016-07-05,139.619400,72.558853,20.817373,89.989998,31.579254,38.907059,25.183807,25.386503,22.840900,6.852908,...,203.486664,6.852908,38.029999,9.219503,NaN,60.992661,39.685646,54.250000,64.979301,39.444118
2016-07-06,144.872391,73.352715,21.305838,90.449997,31.892839,39.014008,25.363140,25.544952,23.150576,6.998167,...,201.431778,6.998167,38.599998,9.320817,NaN,61.179165,39.763161,54.959999,65.170441,40.096802
2016-07-07,144.138535,74.137047,21.678841,93.150002,31.543917,39.014008,25.417717,25.419861,23.704239,7.049438,...,203.180222,7.049438,39.230000,9.356277,NaN,61.179165,38.979443,54.939999,65.126984,42.037262
2016-07-08,146.504272,75.082077,21.971922,94.889999,32.016506,39.645927,26.493681,26.020329,24.145288,7.211787,...,207.713531,7.211787,39.840000,9.645020,NaN,61.730545,39.194759,56.380001,65.761139,43.527882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-25,467.316528,530.865112,55.098900,564.710022,53.908936,55.556805,32.894493,29.012575,73.602478,20.600000,...,441.306427,20.600000,173.820007,14.740000,48.980000,32.910000,59.716522,116.949997,119.080002,70.750000
2021-06-28,468.974274,533.580505,53.082844,556.880005,53.063808,54.448067,32.260002,28.102531,73.103676,20.340000,...,442.123413,20.340000,178.089996,14.530000,48.840000,31.240000,59.597343,116.970001,117.379997,69.989998
2021-06-29,471.490814,541.267700,52.337997,556.890015,53.242775,54.348179,31.920000,27.875021,73.043823,20.059999,...,446.656616,20.059999,178.100006,14.530000,48.540001,31.299999,58.445320,117.430000,116.360001,70.650002
2021-06-30,462.952545,532.192871,52.496899,556.429993,53.352146,54.587910,31.990000,28.092640,72.634811,20.180000,...,436.384644,20.180000,177.020004,14.580000,48.810001,31.270000,58.673744,116.599998,116.620003,71.169998
2021-07-01,463.571686,533.141296,53.450302,564.880005,53.690197,55.137283,32.259998,28.517986,73.392982,20.430000,...,443.199402,20.430000,178.970001,14.700000,48.610001,32.860001,59.656933,117.080002,117.919998,70.860001